version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - cyclop
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - gocritic
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    cyclop:
      max-complexity: 40
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
