linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - contextcheck
    - cyclop
    - durationcheck
    - errname
    - copyloopvar
    - errorlint
    - goimports
    - gosec
    - gocritic

linters-settings:
  cyclop:
    max-complexity: 35
